### ISSUE TITLE
How to train our dataset?

### ISSUE THREAD

**Issue by lwx0724** [xiamenwcy/IrisParseNet#12]
we make the label of pupil mask (setting 1) and iris edge(setting 2), dimension is (N,1,W,H).
But we have a problem with cross entropy.
![iris1](https://user-images.githubusercontent.com/39613095/119110385-ab5dc300-ba54-11eb-8624-41c344e6ed31.png)

![iris2](https://user-images.githubusercontent.com/39613095/119111330-8b7acf00-ba55-11eb-8f3e-7fb07b0bb349.png)

Is  there any problem with the size and dimension of the picture I put？

**Comment by xiamenwcy** [comment]
Please install the correct caffe.
