### ISSUE TITLE
model/training code

### ISSUE THREAD

**Issue by adelbibi** [xiamenwcy/IrisParseNet#3]
Hello,

I do not seem to find the trained model nor the training code. 
Any chances to share the model?

Best,

**Comment by xiamenwcy** [comment]
Code and models will be available upon paper acceptance.

**Comment by xiamenwcy** [comment]
The codes and models have been released.

**Comment by dickyadrian** [comment]
Hi, 

I'd like to download the pretrained model but it seemed that the onedrive link is broken, are there any other alternatives other than baidu?
Thanks
