### ISSUE TITLE
Training model not available on OneDrive

### ISSUE THREAD

**Issue by Pavani14** [xiamenwcy/IrisParseNet#7]
Hi,

I am trying to access the trained models of CASIAv4 and UBIRISv2, however, they do not exist on OneDrive. Could you please upload the same?

**Comment by CHANGErIBE** [comment]
您好！
       我尝试将你公布的模型casia_iris_iter_30000.caffemodel 跑通测试代码test_all_single_scale_general_nir.py，结果报了以下的错误，纠结……
![捕获](https://user-images.githubusercontent.com/32405639/95810151-e5d6e300-0d42-11eb-9fd6-d796850898aa.PNG)
请问如何解决呢？

**Comment by xiamenwcy** [comment]
please use Baidu Drive!
