### ISSUE TITLE
casia_iris_iter_30000.caffemodel 跑测试代码test_all_single_scale_general_nir.py 报错

### ISSUE THREAD

**Issue by CHANGErIBE** [xiamenwcy/IrisParseNet#8]
您好！ 我尝试将你公布的模型casia_iris_iter_30000.caffemodel 跑通测试代码test_all_single_scale_general_nir.py，结果报了以下的错误，纠结……
![捕获](https://user-images.githubusercontent.com/32405639/95810285-29315180-0d43-11eb-89d0-842ee9f16601.PNG)
请问该如何解决呢？

**Comment by xiamenwcy** [comment]
just install my customized caffe framework: https://drive.google.com/file/d/181EsUA6p12eoc7GU-zwSG5M4TxIR_pZZ/view.
please refer to https://github.com/xiamenwcy/extended-caffe for the installation method.
