### ISSUE TITLE
What‘s in the training list ?

### ISSUE THREAD

**Issue by NingCY** [xiamenwcy/IrisParseNet#9]
The root_folder and source should be configured in ImageSegData layer, and I noticed that the SliceLabel layer is behind to get pupil_mask_gt and iris_edge_gt, so what‘s in the training list ? I've check out the two .cpp file, but I can't be sure，could somebody give me some help?

**Comment by xiamenwcy** [comment]
The training list is as follows:
```
train/image/S4000L02_00003.JPEG train/SegmentationClass_1D/S4000L02_00003.png train/pupil_mask_iris_edge/S4000L02_00003.png 
train/image/S4000L04_00005.JPEG train/SegmentationClass_1D/S4000L04_00005.png train/pupil_mask_iris_edge/S4000L04_00005.png 
train/image/S4000L08_00009.JPEG train/SegmentationClass_1D/S4000L08_00009.png train/pupil_mask_iris_edge/S4000L08_00009.png
```

Hence you can make a file "train_mask_edge.txt" to contain such a  training list.  And for  pupil_mask_iris_edge,
you need to generate a new folder "pupil_mask_iris_edge", which contains the label of pupil mask (setting 1) and iris edge(setting 2) in a new label image simultaneously.
